### ISSUE TITLE
Move id string generation to its own module for re-usability.

### ISSUE THREAD

**Issue by mtuchowski** [medikoo/dom-ext#3]
Sometimes it's required to recreate id generated by generate-id for a given name.

**Comment by medikoo** [comment]
You mean something like that -> https://github.com/medikoo/dom-ext/blob/master/html-document/generate-id.js ?

**Comment by mtuchowski** [comment]
I know about this functionality. It's just that it would be nice to have its name to id string functionality reusable.

**Comment by mtuchowski** [comment]
I did a pull request with the functionality I'm after: #4.
